--- # my handlers
- hosts: all
  become: yes
  connection: ssh
  user: ansible
  tasks: 

     - name: installing httpd s/w
       action: yum name=httpd state=present
       notify: start httpd service

  handlers: 

     - name: start httpd service
       action: service name=httpd state=started
