--- # tomcat installation
- hosts: all
  become: yes
  user: ansible
  connection: ssh
  tasks:


      - name: install java
        yum:
           name: java
           state: present
        when: ansible_os_family == "RedHat"


      - name: install java on debian
        apt:
           name: default-jdk
           state: present
        when: ansible_os_family == "Debian"


      - name: download tomcat sowtware
        get_url: 
           url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.85/bin/apache-tomcat-8.5.85.tar.gz
           dest: /opt

      - name: extract tomcat s/w
        unarchive:
            src: /opt/apache-tomcat-8.5.85.tar.gz
            dest: /opt
            remote_src: yes

      - name: providing executable permissions
        file: 
            path: /opt/apache-tomcat-8.5.85/bin/startup.sh
            mode: 0777

      - name: start tomcat service
        shell: nohup ./startup.sh
        args:
            chdir: /opt/apache-tomcat-8.5.85/bin






















