
--- # without handler
- hosts: all
  user: ansible
  connection: ssh
  become: yes
  tasks:

     - name: installing httpd on webservers
       action: yum name=httpd state=present

     - name: service httpd start
       action: service name=httpd state=started
