--- # delete httpd service
- hosts: all
  connection: ssh
  user: ansible
  become: yes
  tasks: 

     - name: delete httpd
       yum:
          name: httpd
          state: absent

     - name: stop httpd service
       service:
           name: httpd
           state: stopped
